--- #YAML:1.0
name:               WebService-Flixster
version:            0.01
abstract:           OO Perl interface to flixster.com
author:
    - Christopher Key <christopher.key@cantab.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cache::FileCache:     0
    Class::Accessor:      0
    DateTime::Incomplete:  0
    File::Spec::Functions:  0
    HTML::Entities:       0
    JSON:                 0
    LWP::UserAgent:       0
    Math::Currency:       0
    URI:                  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
